# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://techgroup.jet.com
gitlocation: https://rachelatjet@jet-tech-blog.scm.azurewebsites.net:443/jet-tech-blog.git
gitbranch: master
title: Welcome to Jet Tech blog.
description: This is the Jet Technology blog

source: source/
blog: source/blog/
videos: source/videos/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: ../jet-tech-blog/
themes: themes