# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://jet.github.io/FsBlog
gitlocation: https://github.com/jet/FsBlog/FsBlog.git
gitbranch: gh-pages
title: Welcome to Jet Technology
description: This is the Jet Technology blog

source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes